services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks:
      - orderly-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 5s
      timeout: 5s
      retries: 15
    restart: unless-stopped
    networks:
      - orderly-network

  userservice:
    build:
      context: ./dotnet
      dockerfile: ./UserService/Dockerfile
    ports:
      - "5002:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Username=postgres;Password=12345678;Database=orderly-userservice-db;
      Jwt__PrivateKeyPath: "/etc/keys/private_key.pem"
      Jwt__PublicKeyPath: "/etc/keys/public_key.pem"
      Jwt__Issuer: "UserService"
      Jwt__Audience: "Client"
      Jwt__AccessTokenExpirationMinutes: "60"
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: guest
      RabbitMq__Password: guest
    volumes:
      - ./dotnet/UserService/Keys/private_key.pem:/etc/keys/private_key.pem:ro
      - ./dotnet/UserService/Keys/public_key.pem:/etc/keys/public_key.pem:ro
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - orderly-network

  productservice:
    build:
      context: ./dotnet
      dockerfile: ./ProductService/Dockerfile
    ports:
      - "5003:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=postgres;Port=5432;Username=postgres;Password=12345678;Database=orderly-productservice-db;
      Jwt__PublicKeyPath: "/etc/keys/public_key.pem"
      Jwt__Issuer: "UserService"
      Jwt__Audience: "Client"
      RabbitMq__Host: rabbitmq
      RabbitMq__Username: guest
      RabbitMq__Password: guest
    volumes:
      - ./dotnet/UserService/Keys/public_key.pem:/etc/keys/public_key.pem:ro
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - orderly-network

  cartservice:
    build:
      context: ./java/cartservice
      dockerfile: ./src/main/docker/Dockerfile.jvm
    ports:
      - "5004:8080"
    environment:
      QUARKUS_DATASOURCE_JDBC_URL: "jdbc:postgresql://postgres:5432/orderly-cartservice-db"
      QUARKUS_DATASOURCE_USERNAME: "postgres"
      QUARKUS_DATASOURCE_PASSWORD: "12345678"
      
      MP_MESSAGING_OUTGOING_CART_EVENTS_HOST: "rabbitmq"
      MP_MESSAGING_OUTGOING_CART_EVENTS_PORT: 5672
      MP_MESSAGING_OUTGOING_CART_EVENTS_USERNAME: "guest"
      MP_MESSAGING_OUTGOING_CART_EVENTS_PASSWORD: "guest"
      
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_HOST: "rabbitmq"
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_PORT: 5672
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_USERNAME: "guest"
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_PASSWORD: "guest"
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_EXCHANGE_NAME: "ProductCreatedEvent"
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_EXCHANGE_TYPE: "fanout"
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_QUEUE_NAME: "product-created"
      MP_MESSAGING_INCOMING_PRODUCT_CREATED_ROUTING_KEYS: "#"
      
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_HOST: "rabbitmq"
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_PORT: 5672
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_USERNAME: "guest"
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_PASSWORD: "guest"
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_EXCHANGE_NAME: "ProductUpdatedEvent"
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_EXCHANGE_TYPE: "fanout"
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_QUEUE_NAME: "product-updated"
      MP_MESSAGING_INCOMING_PRODUCT_UPDATED_ROUTING_KEYS: "#"
      
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_HOST: "rabbitmq"
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_PORT: 5672
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_USERNAME: "guest"
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_PASSWORD: "guest"
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_EXCHANGE_NAME: "ProductDeletedEvent"
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_EXCHANGE_TYPE: "fanout"
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_QUEUE_NAME: "product-deleted"
      MP_MESSAGING_INCOMING_PRODUCT_DELETED_ROUTING_KEYS: "#"
      
      MP_JWT_VERIFY_PUBLICKEY_LOCATION: "file:/etc/keys/public_key.pem"
      MP_JWT_VERIFY_ISSUER: "UserService"
      MP_JWT_VERIFY_AUDIENCES: "Client"
      MP_JWT_TOKEN_HEADER: "Authorization"
      MP_JWT_VERIFY_ALGORITHM: "RS256"

      MP_JWT_VERIFY_GROUPS_PATH: "role"
      SMALLRYE_JWT_PATH_GROUPS: "role"
      SMALLRYE_JWT_CLAIMS_GROUPS: "role"

      SMALLRYE_JWT_REQUIRE_NAMED_PRINCIPAL: "false"
      SMALLRYE_JWT_PATH_MAPPING: "/=/"
      
      QUARKUS_LOG_CATEGORY_IO_SMALLRYE_JWT_LEVEL: "DEBUG"
      QUARKUS_LOG_CATEGORY_IO_QUARKUS_SECURITY_LEVEL: "DEBUG"
      QUARKUS_LOG_LEVEL: "DEBUG"
      
      QUARKUS_SWAGGER_UI_ALWAYS_INCLUDE: "true"
      QUARKUS_SWAGGER_UI_PERSIST_AUTHORIZATION: "true"
      QUARKUS_SMALLRYE_OPENAPI_SECURITY_SCHEME: "jwt"
      QUARKUS_SMALLRYE_OPENAPI_SECURITY_SCHEME_NAME: "bearerAuth"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
       - ./dotnet/UserService/Keys/public_key.pem:/etc/keys/public_key.pem:ro
    restart: unless-stopped
    networks:
      - orderly-network

volumes:
  pgdata:

networks:
  orderly-network:
    driver: bridge